Feature/common/link-button (#1, #2, #7, #8)
boostcamp-2020/IssueTracker-31 pull request #130
Opened 2020-11-04 09:57 UTC by batboy118

## Linked Issue
Close #1 , #2 , #7 , #8 

## 공유할 사항
- Button 기존에 있던 Button 컴포넌트를 수정하였습니다.
- Button의 종류에 따라 다른 스타일을 적용 시킬 수 있도록 getButtonProps 함수를 만들었는데 파일이 너무 길어져서 마음에 들지 않습니다.
- label이나 milestone 페이지에서는 해당 LinkButton이 파란색으로 보여져야 하는데 ,그때 정보는 Page파일에서 LinkButton컴포넌트로 page props로 정보를 넘겨주면 파란색이 적용되도록 만들었습니다.
- Button 컴포넌트에는 name props를 넘겨주어야 합니다. 

## 논의할 사항
- milestone, label의 수를 계산할 때 issueList의 context API를 사용하여 받아서 사용하고 있는데, 다른 페이지에서도 해당 값이 필요합니다. 하지만, 다른 List의 context까지 모두 받아버리면 조금 비효율 적일 것 같습니다.
- LinkButton 컴포넌트에서 page를 확인해서 Button으로 해당 페이지의 컨텍스트를 넘겨주는 방식으로 하면 어떨까요?

2020-11-04 15:32 UTC, solo95 approved these changes
고생하셨습니다!

2020-11-04 15:32 UTC, solo95 commented on frontend/src/component/common/Button.js
> +      props.symbol =
svg는 파일을 따로 관리하면 어떨까요?

2020-11-04 15:32 UTC, solo95 commented on frontend/src/component/common/Button.js
> +const getButtonProps = (name, context, selected) => {
style, to, count, symbol을 한번에 처리해서 getButtonProps 함수의 크기가 커진 것 같습니다.
각각의 기능을 나누어 보면 어떨까요?

2020-11-04 18:05 UTC, hyex requested changes
여러 케이스를 고려하면서 재사용할 컴포넌트를 구현하는 게 졍말 어려운 것 같습니다... 수고하셨어요!

오늘 올려주신 코드만 봤을 때는 IssueListPage에서만 사용하는 Button 의 의미가 강한 것 같아요.
상위 컴포넌트에서 props를 받아서 처리하기 보다는 버튼 컴포넌트 내에서 분기 처리를 하기 때문에 그런 것 같습니다.

버튼이 사용되는 경우를 생각해보자면,
[1] IssueListPage - LinkButton 
[2] IssueListPage - New Issue Button
[3] CreateIssuePage - Cancel, Submit new issue Button
[4] LabelPage/MilestonePage - TabButton
[5-1] LabelPage - New Label Button
[5-2] MilestonePage - New Milestone Button
[6] IssueDetailPage - Comment의 Cancel/Update comment, Issue의 Close issue/Comment

정도가 있는 것 같습니다. 케이스마다 다른 점을 정리해보면

1. 버튼 안에 들어가는 그림과 글자
    - [1] 아이콘(=심볼), 텍스트, 카운트
    - [2,3,5,6] 텍스트
    - [4,6] 아이콘, 텍스트
-> 지금 생각나는 해결 방법) 이 경우는 `props.children`으로 처리 가능할 것 같습니다.
2. 액션
    - [1,2,4,5-2] 라우터(url) 이동
    - [5-1] 같은 페이지 내에서 어떤 컴포넌트를 보이게/안보이게
    - [3,6] 서버로 요청 보내고 redirect/또는 액션 취소 등 다른 모든 케이스
-> 지금 생각나는 해결 방법) `targetLocation`이라는 props를 보내면 라우터 이동이라는 뜻으로 해석하여 `<Link`> 컴포넌트로 감싸고, 저 props가 없다면 `onClick` 함수를 props로 보내게 해서 라우터 이동이 아닌 다른 케이스를 모두 처리
3. style
    - background color, color, hover color 
-> 지금 생각나는 해결 방법) 상위 컴포넌트에서 계산을 하고 결정한 색깔을 넘긴다.

지금 당장 생각나는 건 이 정돈데 이런 식으로 정리해보면서 버튼 컴포넌트를 개선할 수 있을 것 같습니다 ! (지금 기획서 보면서 막 정리한 거라 그리 정확하진 않습니다)
그리고, 오늘 Label 컴포넌트 구현하면서 Button 컴포넌트 파일을 좀 건드렸는데 이 부분도 내일 얘기해보고 싶습니당

2020-11-04 18:05 UTC, hyex commented on frontend/src/component/common/Button.js
> +import { issueListContext } from '@Page/IssueList'
`issueListContext`를 사용하는 순간 이 `Button` 컴포넌트는 다른 페이지에서 재사용이 불가능 할 것 같습니다. 필요한 값을 `props`로 전달 받는 방법은 어떤가요?

2020-11-04 18:05 UTC, hyex commented on frontend/src/component/common/Button.js
> +      props.symbol =
덧붙이자면, 저도 오늘 개발하면서 svg 파일을 사용할 일이 있어서 svg를 따로 `public` 경로에 js 파일로 분리하고, 이를 import해서 넣어주는 방식을 사용했습니다. 이게 맞는 방법인지는 모르겠으나 이와 유사하게 파일을 분리하고, 해당 svg를 props로 넘겨주면 분기 처리가 필요가 없어지고 재사용성이 높아지지 않을까요?

2020-11-04 18:05 UTC, hyex commented on frontend/src/component/common/Button.js
> +      {count !== undefined ? <StyledSpan>{count}</StyledSpan> : ''}
버튼에 count 가 들어가는 경우가 issue List 페이지뿐이지 않나요?!
저도 써본 건 아니지만[ `props.children`](https://react.vlpt.us/basic/05-props.html)을 사용하면 버튼 컴포넌트를 사용하는 곳, 즉 부모 컴포넌트에서 넣은 엘리먼트를  넘겨줄 수 있다고 합니다!
```
<Button>
    <div>8</div>
</Button>
```

혹시 이 방법을 사용해서 symbol, name, count를 모두 부모 컴포넌트에서 처리할 수 있다면 좋을 것 같아요!
예시입니다.
![image](https://user-images.githubusercontent.com/48546343/98150068-6f786b80-1f11-11eb-8592-0e421b316c13.png)

2020-11-05 01:34 UTC, zunopark approved these changes
고생 많으셨습니다!

2020-11-05 08:29 UTC, hyex approved these changes

2020-11-05 08:30 UTC, merged